name: server
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  mongo_dart: ^0.2.10
  connection_pool: ^0.1.2
  option: ^1.2.0
  rpc: ^0.5.7
  di: ^3.0.0
  shelf: ^0.6.5
  shelf_auth: ^0.7.3
  shelf_route: ^0.14.3
  shelf_rpc: ^0.0.3
  shelf_static: ^0.2.5
  shelf_exception_handler: ^0.1.0
  logging_handlers: ^0.8.0

  hex: ^0.1.1
  tools:
    path: ../tools
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
